import { Group, Rect, Circle, Arc, Text } from 'react-konva'
import type { AccessPointElement } from '../../../types/elements'
import { useUIStore } from '../../../stores/uiStore'
import { truncateToWidth } from '../../../lib/textTruncate'

interface Props {
  element: AccessPointElement
}

/**
 * Threshold for dropping the under-element label. APs are small by
 * default (30×30) so the label is normally suppressed; when a user
 * resizes the AP up — say, to mark a high-density coverage zone — the
 * label re-emerges. Same `< 48` width threshold the table renderer
 * uses for its id badge so the rule reads consistently across types.
 */
const TOO_SMALL_FOR_LABEL = (w: number, h: number) => w < 48 || h < 36

/**
 * Wireless access-point renderer.
 *
 * Visual identity is a soft white disc with a blue accent ring, three
 * concentric "wifi" arcs in the upper half, and a small center dot —
 * the radio-tower silhouette commercial AV/IT drawings use to denote
 * a ceiling-mounted Wi-Fi radio. The arcs convey "signal radiating
 * outward" without implying a directional antenna (most APs are
 * omnidirectional).
 *
 * Status overrides:
 *   - `'broken'`  swaps the accent stroke to red and adds a red center
 *                 dot, so the broken state is visible on a small floor
 *                 plan without needing the label.
 *   - `'planned'` switches the outer ring to a dashed stroke to
 *                 communicate "future install" without changing the
 *                 colour story.
 */
export function AccessPointRenderer({ element }: Props) {
  const selectedIds = useUIStore((s) => s.selectedIds)
  const isSelected = selectedIds.includes(element.id)

  const w = element.width
  const h = element.height
  const r = Math.min(w, h) / 2

  const isBroken = element.deviceStatus === 'broken'
  const isPlanned = element.deviceStatus === 'planned'

  const accent = isBroken ? '#DC2626' : element.style.stroke
  const stroke = isSelected ? '#3B82F6' : accent
  const strokeWidth = isSelected ? 2.5 : element.style.strokeWidth
  const dash = isPlanned ? [4, 3] : undefined

  // Prefer model name when present (IT folks recognise APs by model
  // far faster than by an autogenerated label). Falls back to label.
  const labelText = element.model ?? element.label
  const showLabel = !TOO_SMALL_FOR_LABEL(w, h) && !!labelText

  return (
    <Group rotation={element.rotation} listening={!element.locked}>
      {/* Outer disc — full corner radius makes a circle even when the
       *  user resizes the bounds non-square. The rect form is used
       *  rather than Circle so the bounds anchor matches every other
       *  renderer's center-origin contract. */}
      <Rect
        x={-w / 2}
        y={-h / 2}
        width={w}
        height={h}
        fill={element.style.fill}
        stroke={stroke}
        strokeWidth={strokeWidth}
        cornerRadius={Math.max(w, h)}
        opacity={element.style.opacity}
        dash={dash}
      />
      {/* Wifi arcs — three concentric arcs in the upper half of the
       *  disc. Drawn from 220°→320° so the "fan" opens upward while
       *  staying inside the disc bounds. Sized as fractions of `r` so
       *  they scale with resizes. */}
      {[0.45, 0.65, 0.85].map((scale, i) => (
        <Arc
          key={i}
          innerRadius={r * scale}
          outerRadius={r * scale + Math.max(0.6, r * 0.05)}
          angle={100}
          rotation={220}
          fill={accent}
          opacity={element.style.opacity * (0.7 - i * 0.15)}
          listening={false}
        />
      ))}
      {/* Center dot — the radio "source". Red when broken so the
       *  problem reads at a glance even when the disc is small. */}
      <Circle
        radius={Math.max(1.5, r * 0.12)}
        fill={isBroken ? '#DC2626' : accent}
        opacity={element.style.opacity}
        listening={false}
      />
      {showLabel && (
        <Text
          text={truncateToWidth(labelText, Math.max(20, w + 12), 9)}
          x={-w / 2 - 6}
          y={h / 2 + 2}
          width={w + 12}
          align="center"
          fontSize={9}
          fill="#374151"
          listening={false}
        />
      )}
    </Group>
  )
}
