/**
 * View-only share link. Generated by an editor/owner to grant anonymous
 * read-only access to a single office's map + redacted roster for a
 * bounded time window.
 *
 * The token is a high-entropy opaque string (see `shareLinksStore.create`)
 * — it is the only bearer credential, so leaking it is equivalent to
 * leaking the office view. Revocation is a soft-delete (`revokedAt`) so
 * existing rows persist for audit.
 */
export interface ShareLink {
  id: string
  token: string
  officeId: string
  createdBy: string | null
  createdByName: string | null
  createdAt: string
  expiresAt: string
  revokedAt: string | null
  /** Optional human-readable tag, e.g. "board review" or "Q2 exec". */
  label: string | null
}
